### ISSUE TITLE
indices access problem

### ISSUE THREAD

**Issue by ri0day** [thm1118/kibana-auth--xpack-plugin#1]
hi , thm1118, i was installed your plugin on kibana 5.1.1 .
the authentication part is working great..
but the user can not access the index  which specificed in my kibana.yml .

env:
kibana 5.1.1 
elasticsearch 5.1.1

kibana.yml  config file  add

```
security:
  encryptionKey: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
  cookieName: 'mycookie'
  users: [{'username':'kibana', 'password':'changeme','full_name':'admin', 'index':'logstash-*','metadata':{'_reserved':true}},{'username':'log2', 'password':'changeme','index':'log2-*','metadata':{'_reserved':true}}]

```

http log file
`Dec 29 10:25:44 elkstack-labs-vnode1 kibana[4664]: {"type":"log","@timestamp":"2016-12-29T02:25:44Z","tags":["info","onPreHandler事件 请求索引名"],"pid":4664,"message":"logstash-*"}
Dec 29 10:25:45 elkstack-labs-vnode1 kibana[4664]: {"type":"response","@timestamp":"2016-12-29T02:25:44Z","tags":[],"pid":4664,"method":"post","statusCode":200,"req":{"url":"/elasticsearch/logstash-*/_field_stats?level=indices","method":"post","headers":{"host":"192.168.33.10:5601","connection":"keep-alive","content-length":"178","accept":"application/json, text/plain, */*","origin":"http://192.168.33.10:5601","kbn-version":"5.1.1","user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36","content-type":"application/json","referer":"http://192.168.33.10:5601/app/kibana","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.8"},"remoteAddress":"192.168.33.1","userAgent":"192.168.33.1","referer":"http://192.168.33.10:5601/app/kibana"},"res":{"statusCode":200,"responseTime":272,"contentLength":9},"message":"POST /elasticsearch/logstash-*/_field_stats?level=indices 200 272ms - 9.0B"}
Dec 29 10:25:45 elkstack-labs-vnode1 kibana[4664]: {"type":"log","@timestamp":"2016-12-29T02:25:45Z","tags":["info","======onRequest事件--payload"],"pid":4664,"message":"/elasticsearch/_msearch"}
Dec 29 10:25:45 elkstack-labs-vnode1 kibana[4664]: {"type":"log","@timestamp":"2016-12-29T02:25:45Z","tags":["info","======onPreHandler事件--payload-index-jso 请求索引名 index"],"pid":4664,"message":"logstash-2016.12.29"}
Dec 29 10:25:45 elkstack-labs-vnode1 kibana[4664]: {"type":"response","@timestamp":"2016-12-29T02:25:45Z","tags":[],"pid":4664,"method":"post","statusCode":403,"req":{"url":"/elasticsearch/_msearch","method":"post","headers":{"host":"192.168.33.10:5601","connection":"keep-alive","content-length":"835","accept":"application/json, text/plain, */*","origin":"http://192.168.33.10:5601","kbn-version":"5.1.1","user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36","content-type":"application/x-ldjson","referer":"http://192.168.33.10:5601/app/kibana","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.8"},"remoteAddress":"192.168.33.1","userAgent":"192.168.33.1","referer":"http://192.168.33.10:5601/app/kibana"},"res":{"statusCode":403,"responseTime":70,"contentLength":9},"message":"POST /elasticsearch/_msearch 403 70ms - 9.0B"}
`
